name: PaintZone
version: 1.0.0
main: com.mycompany.testplugin.PaintZone
api-version: 1.19
author: Matt
description: Paint Zone minigame plugin

commands:
  pz:
    description: Main PaintZone command
    usage: /pz <args>
  pzadmin:
    description: PaintZone admin commands
    usage: /pzadmin <args>